# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\UI\sowe\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from Custom_Widgets.Widgets import *

class login_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(307, 425)
        MainWindow.setStyleSheet("*{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    background:transparent;\n"
"    padding:0;\n"
"    margin:0;\n"
"}\n"
"#loginContainer{\n"
"    border:none;\n"
"    background-color: #F8DE7E;\n"
"    border-radius:10px ;\n"
"}\n"
"#lineEdit, #lineEdit_2, #userIdLine, #passwordLine, #confrimPasswordLine{\n"
"    background-color:rgba(0, 0, 0, 0);\n"
"    border:1px solid rgba(0, 0, 0, 0);\n"
"    border-bottom-color:rgba(46, 82, 101, 255);\n"
"    color:rgb(0, 0, 0);\n"
"    padding-bottom:7px\n"
"}\n"
"QPushButton#pushButton,QPushButton#pushButton_2, QPushButton#createAccountBtn, QPushButton#createBtn, QPushButton#goToLoginBtn{\n"
"background-color:#FFE482;\n"
"color:rgba(0, 0, 0, 200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:pressed,QPushButton#pushButton_2:pressed, QPushButton#createAccountBtn:pressed,QPushButton#createBtn:pressed,QPushButton#goToLoginBtn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:#FFE482;\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#pushButton:hover,QPushButton#pushButton_2:hover\n"
",QPushButton#createAccountBtn:hover,QPushButton#createBtn:hover,QPushButton#goToLoginBtn:hover{\n"
"background-color:#EDD478;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.loginContainer = QtWidgets.QWidget(self.centralwidget)
        self.loginContainer.setGeometry(QtCore.QRect(10, 10, 290, 410))
        self.loginContainer.setStyleSheet("")
        self.loginContainer.setObjectName("loginContainer")
        self.frame = QtWidgets.QFrame(self.loginContainer)
        self.frame.setGeometry(QtCore.QRect(0, 0, 290, 410))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.loginPages = QtWidgets.QStackedWidget(self.frame)
        self.loginPages.setGeometry(QtCore.QRect(0, 0, 290, 410))
        self.loginPages.setObjectName("loginPages")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.lineEdit = QtWidgets.QLineEdit(self.loginPage)
        self.lineEdit.setGeometry(QtCore.QRect(20, 210, 250, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.loginPage)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 260, 250, 30))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.loginPage)
        self.pushButton.setGeometry(QtCore.QRect(20, 320, 125, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.createBtn = QtWidgets.QPushButton(self.loginPage)
        self.createBtn.setGeometry(QtCore.QRect(145, 320, 125, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.createBtn.setFont(font)
        self.createBtn.setObjectName("createBtn")
        self.label = QtWidgets.QLabel(self.loginPage)
        self.label.setGeometry(QtCore.QRect(60, 15, 180, 180))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/images/login_sowemusic.png"))
        self.label.setObjectName("label")
        self.loginPages.addWidget(self.loginPage)
        self.createPage = QtWidgets.QWidget()
        self.createPage.setObjectName("createPage")
        self.userIdLine = QtWidgets.QLineEdit(self.createPage)
        self.userIdLine.setGeometry(QtCore.QRect(20, 160, 250, 30))
        self.userIdLine.setObjectName("userIdLine")
        self.passwordLine = QtWidgets.QLineEdit(self.createPage)
        self.passwordLine.setGeometry(QtCore.QRect(20, 210, 250, 30))
        self.passwordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLine.setObjectName("passwordLine")
        self.confrimPasswordLine = QtWidgets.QLineEdit(self.createPage)
        self.confrimPasswordLine.setGeometry(QtCore.QRect(20, 260, 250, 30))
        self.confrimPasswordLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confrimPasswordLine.setObjectName("confrimPasswordLine")
        self.createAccountBtn = QtWidgets.QPushButton(self.createPage)
        self.createAccountBtn.setGeometry(QtCore.QRect(20, 320, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.createAccountBtn.setFont(font)
        self.createAccountBtn.setObjectName("createAccountBtn")
        self.goToLoginBtn = QtWidgets.QPushButton(self.createPage)
        self.goToLoginBtn.setGeometry(QtCore.QRect(145, 370, 125, 23))
        self.goToLoginBtn.setObjectName("goToLoginBtn")
        self.loginPages.addWidget(self.createPage)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(250, 10, 41, 21))
        self.pushButton_6.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_6.setObjectName("pushButton_6")
        self.loginSizeGrip = QtWidgets.QWidget(self.frame)
        self.loginSizeGrip.setGeometry(QtCore.QRect(280, 400, 10, 10))
        self.loginSizeGrip.setMaximumSize(QtCore.QSize(10, 10))
        self.loginSizeGrip.setObjectName("loginSizeGrip")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.loginPages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "User ID"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton.setText(_translate("MainWindow", "Log in"))
        self.createBtn.setText(_translate("MainWindow", "Create an account"))
        self.userIdLine.setPlaceholderText(_translate("MainWindow", "User ID"))
        self.passwordLine.setPlaceholderText(_translate("MainWindow", "Password"))
        self.confrimPasswordLine.setPlaceholderText(_translate("MainWindow", "Confirm Password"))
        self.createAccountBtn.setText(_translate("MainWindow", "Create an account"))
        self.goToLoginBtn.setText(_translate("MainWindow", "Go to Login page"))
import resources_login_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
